#!/usr/bin/env node
'use strict';
// Writes the persona data the ClaudeWhip mod draws with, from lib/personas.js
// (the single source of truth), as an ES module the mod imports:
//   node scripts/build-mod.js [mod-folder]   (default: mod/whip-desk)
// A mod runs without Node, so it can't require lib/ itself.
const fs = require('fs');
const path = require('path');
const personas = require('../lib/personas');

const out = path.resolve(process.argv[2] || path.join(__dirname, '..', 'mod', 'whip-desk'));
const data = {};
for (const p of Object.values(personas.BUILTIN)) {
  data[p.id] = { id: p.id, name: p.name, blurb: p.blurb, whack: p.whack, faces: p.faces, lines: p.lines };
}
const src = `// Generated by scripts/build-mod.js from lib/personas.js. Do not edit.
import type { WhipPersona } from '../types'

export const CLASSIC: WhipPersona = ${JSON.stringify(data.classic, null, 2)}

export const PERSONAS: Record<string, WhipPersona> = ${JSON.stringify(data, null, 2)}
`;
fs.mkdirSync(path.join(out, 'hooks'), { recursive: true });
fs.writeFileSync(path.join(out, 'hooks', 'personas.ts'), src);
console.log(`wrote ${path.join(out, 'hooks', 'personas.ts')} (${Object.keys(data).join(', ')})`);
