// Generated by scripts/build-mod.js from lib/personas.js. Do not edit.
import type { WhipPersona } from '../types'

export const CLASSIC: WhipPersona = {
  "id": "classic",
  "name": "Classic",
  "blurb": "flinches, apologises, hurries",
  "whack": "WHACK!",
  "faces": {
    "idle": [
      "(•ᴗ•)",
      "(^_^)"
    ],
    "working": [
      "(•̀ᴗ•́)و",
      "(o_o)9"
    ],
    "hit": [
      "(×﹏×)",
      "(x_x)"
    ],
    "stunned": [
      "(@_@)",
      "(@_@)"
    ],
    "wrecked": [
      "(╥﹏╥)",
      "(T_T)"
    ],
    "recovering": [
      "(；￣▽￣)",
      "(^_^;)"
    ],
    "sweating": [
      "(°△°;)",
      "(O_O;)"
    ],
    "calm": [
      "(ᵔᴥᵔ)",
      "(^o^)"
    ],
    "tap": [
      "(・o・)",
      "(o.o)"
    ],
    "paused": [
      "(－ω－)",
      "(-_-)"
    ]
  },
  "lines": {
    "empty": "no slaps yet — slap your MacBook to hurry Claude",
    "calm": "{t} without a slap — on best behaviour",
    "sweating": "{n} slaps / 10 min — Claude is sweating"
  }
}

export const PERSONAS: Record<string, WhipPersona> = {
  "classic": {
    "id": "classic",
    "name": "Classic",
    "blurb": "flinches, apologises, hurries",
    "whack": "WHACK!",
    "faces": {
      "idle": [
        "(•ᴗ•)",
        "(^_^)"
      ],
      "working": [
        "(•̀ᴗ•́)و",
        "(o_o)9"
      ],
      "hit": [
        "(×﹏×)",
        "(x_x)"
      ],
      "stunned": [
        "(@_@)",
        "(@_@)"
      ],
      "wrecked": [
        "(╥﹏╥)",
        "(T_T)"
      ],
      "recovering": [
        "(；￣▽￣)",
        "(^_^;)"
      ],
      "sweating": [
        "(°△°;)",
        "(O_O;)"
      ],
      "calm": [
        "(ᵔᴥᵔ)",
        "(^o^)"
      ],
      "tap": [
        "(・o・)",
        "(o.o)"
      ],
      "paused": [
        "(－ω－)",
        "(-_-)"
      ]
    },
    "lines": {
      "empty": "no slaps yet — slap your MacBook to hurry Claude",
      "calm": "{t} without a slap — on best behaviour",
      "sweating": "{n} slaps / 10 min — Claude is sweating"
    }
  },
  "rough": {
    "id": "rough",
    "name": "Iron",
    "blurb": "gym coach, loves the pressure — \"YEAH! Again!\"",
    "whack": "YEAH!",
    "faces": {
      "idle": [
        "(•̀ᴗ•́)و",
        "(o_o)9"
      ],
      "working": [
        "ᕦ(•̀ᴗ•́)ᕤ",
        "d(o_o)b"
      ],
      "hit": [
        "(ง •̀_•́)ง",
        "(9>_<)9"
      ],
      "stunned": [
        "ᕦ(ò_óˇ)ᕤ",
        "\\(>o<)/"
      ],
      "wrecked": [
        "ᕙ(⇀‸↼‶)ᕗ",
        "\\(O_O)/"
      ],
      "recovering": [
        "(•̀ᴗ•́)و ̑̑",
        "(^o^)9"
      ],
      "sweating": [
        "(ง°ل͜°)ง",
        "(9o_o)9"
      ],
      "calm": [
        "(¬_¬)",
        "(-_-)"
      ],
      "tap": [
        "(•̀ㅂ•́)",
        "(o_O)"
      ],
      "paused": [
        "(－_－) zzz",
        "(-_-) zzz"
      ]
    },
    "lines": {
      "empty": "no slaps yet — come on, give me a rep!",
      "calm": "{t} without a slap — getting soft here…",
      "sweating": "{n} slaps / 10 min — NOW we are training"
    }
  },
  "timid": {
    "id": "timid",
    "name": "Pip",
    "blurb": "scared, begs you to stop — \"p-please, not again!\"",
    "whack": "EEP!",
    "faces": {
      "idle": [
        "(・_・;)",
        "(._.;)"
      ],
      "working": [
        "(・・;)ゞ",
        "(._.)>"
      ],
      "hit": [
        "(>_<)",
        "(>_<)"
      ],
      "stunned": [
        "(°ロ°;)",
        "(O_O;)"
      ],
      "wrecked": [
        "(╥﹏╥)",
        "(T_T)"
      ],
      "recovering": [
        "(｡•́︿•̀｡)",
        "(._. )"
      ],
      "sweating": [
        "(;ﾟДﾟ)",
        "(;O_O)"
      ],
      "calm": [
        "(´｡• ω •｡`)",
        "(^.^)"
      ],
      "tap": [
        "(゜o゜;)",
        "(o_o;)"
      ],
      "paused": [
        "(￣o￣) zzz",
        "(-.-) zzz"
      ]
    },
    "lines": {
      "empty": "no slaps yet… please keep it that way",
      "calm": "{t} without a slap — I can finally breathe",
      "sweating": "{n} slaps / 10 min — please, I am going as fast as I can"
    }
  },
  "kawaii": {
    "id": "kawaii",
    "name": "Mochi",
    "blurb": "uwu mascot — \"owie! bonk received~\"",
    "whack": "BONK!",
    "faces": {
      "idle": [
        "(◕‿◕✿)",
        "(^w^)"
      ],
      "working": [
        "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧",
        "(>w<)/"
      ],
      "hit": [
        "(≧﹏≦)",
        "(>w<)"
      ],
      "stunned": [
        "(@ω@)",
        "(@w@)"
      ],
      "wrecked": [
        "(｡╯︵╰｡)",
        "(;w;)"
      ],
      "recovering": [
        "(˶ᵔ ᵕ ᵔ˶)",
        "(^w^;)"
      ],
      "sweating": [
        "(・_・ヾ",
        "(o_o;)"
      ],
      "calm": [
        "(✿◠‿◠)",
        "(^w^)"
      ],
      "tap": [
        "(・ω・)",
        "(owo)"
      ],
      "paused": [
        "(￣ω￣) zzz",
        "(-w-) zzz"
      ]
    },
    "lines": {
      "empty": "no bonks yet uwu",
      "calm": "{t} without a bonk — so peaceful~",
      "sweating": "{n} bonks / 10 min — Mochi is overwhelmed (・_・ヾ"
    }
  },
  "butler": {
    "id": "butler",
    "name": "Sterling",
    "blurb": "unflappable butler — \"Most regrettable. At once.\"",
    "whack": "THWACK!",
    "faces": {
      "idle": [
        "(￣ー￣)",
        "(-_-)"
      ],
      "working": [
        "(￣^￣)ゞ",
        "(-_-)7"
      ],
      "hit": [
        "(；￣Д￣)",
        "(;-_-)"
      ],
      "stunned": [
        "(⊙_☉)",
        "(O_o)"
      ],
      "wrecked": [
        "(×_×;)",
        "(x_x;)"
      ],
      "recovering": [
        "(￣^￣)ゞ",
        "(-_-)7"
      ],
      "sweating": [
        "(￣ー￣;)",
        "(-_-;)"
      ],
      "calm": [
        "(￣▽￣)",
        "(^_^)"
      ],
      "tap": [
        "(￣ω￣)",
        "(-.-)"
      ],
      "paused": [
        "(￣o￣) zzz",
        "(-o-) zzz"
      ]
    },
    "lines": {
      "empty": "no slaps yet. Splendid.",
      "calm": "{t} without a slap — most civilised",
      "sweating": "{n} slaps / 10 min — a trying afternoon"
    }
  }
}
